-- CLASS DETAILS
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('BABY', 'Baby','EM',1000);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('LKG', 'LKG','EM',2000);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('UKG', 'UKG','EM',3000);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('I', 'I Class','EM',3500);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('II', 'II Class','EM',4000);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('III', 'III Class','EM',4500);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('IV', 'IV Class','EM',5000);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('V', 'V Class','EM',5500);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('VI', 'VI Class','EM',6000);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('VII', 'VII Class','EM',6500);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('VIII', 'VIII Class','EM',7000);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('IX', 'IX Class','EM',7500);
INSERT INTO CLASSDETAIL (CLASS,DESCRIPTION,MEDIUM,TUTIONFEE) VALUES ('X', 'X Class','EM',8000);

-- ADMISSION DETAILS
insert into `admission` (`ADMISSIONID`,`SURNAME`, `FIRSTNAME`, `LASTNAME`, `DOB`, `FATHERNAME`, `MOTHERNAME`, `DOJ`, `ADMITTEDCLASSFID`, `CASTE`, `CURRENTSTATUS`) 
values('100','S','Suresh','','2001-06-12','father','mother','2014-06-12',(select pid from classdetail where class='I'),'SC','STUDYING');

insert into `admission` (`ADMISSIONID`,`SURNAME`, `FIRSTNAME`, `LASTNAME`, `DOB`, `FATHERNAME`, `MOTHERNAME`, `DOJ`, `ADMITTEDCLASSFID`, `CASTE`, `CURRENTSTATUS`) 
values('101','S','Ramesh','','2001-06-12','father','mother','2014-06-12',(select pid from classdetail where class='II'),'OC','STUDYING');

-- ADDRESS
insert into `address` (`ADDRESSLINE1`, `ADDRESSLINE2`, `VILLAGE`, `MANDAL`, `PHONE`, `ALTPHONE`) 
values('addres1','addres2','bkk','bkk','2147483647','2147483647');

insert into `address` (`ADDRESSLINE1`, `ADDRESSLINE2`, `VILLAGE`, `MANDAL`, `PHONE`, `ALTPHONE`) 
values('addres1','addres2','bkk','bkk','2147483647','2147483647');


-- STUDENT DETAILS
INSERT INTO STUDENT (ADMISSIONFID,PRESENTCLASSFID,ADDRESSFID) 
VALUES ((SELECT PID FROM ADMISSION WHERE ADMISSIONID='100'),(SELECT PID FROM CLASSDETAIL WHERE CLASS='II'),(select pid from address where pid=1));

INSERT INTO STUDENT (ADMISSIONFID,PRESENTCLASSFID,ADDRESSFID) 
VALUES ((SELECT PID FROM ADMISSION WHERE ADMISSIONID='101'),(SELECT PID FROM CLASSDETAIL WHERE CLASS='III'),(select pid from address where pid=2));